test:
  name: "Hyperledger Fabric v2.5.9 - Benchmark network"
  workers:
    type: local
    number: 5
  rounds:
    - label: Create Asset - Validation Round
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: benchmarks/createAsset.js

    - label: Query Asset - Node chaincode
      description: Get Asset.
      txNumber: 10000
      rateControl:
        type: fixed-rate
        opts:
          tps: 700
      workload:
        module: benchmarks/queryAsset.js