# Definition of nodes
peer1: &peer1
  addr: localhost:7051
  ssl_target_name_override: peer0.org1.example.com
  org: org1
  tls_ca_cert: ../../artifacts/channel/crypto-config/peerOrganizations/org1.example.com/msp/tlscacerts/ca.crt

peer2: &peer2
  addr: localhost:9051
  ssl_target_name_override: peer0.org2.example.com
  org: org2
  tls_ca_cert: ../../artifacts/channel/crypto-config/peerOrganizations/org1.example.com/msp/tlscacerts/ca.crt

peer3: &peer3
  addr: localhost:11051
  ssl_target_name_override: peer0.org3.example.com
  org: org3
  tls_ca_cert: ../../artifacts/channel/crypto-config/peerOrganizations/org1.example.com/msp/tlscacerts/ca.crt

# peer2: &peer2
#   addr: localhost:9051
#   tls_ca_cert: ../../artifacts/channel/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

orderer: &orderer
  addr: localhost:7050
  ssl_target_name_override: orderer.example.com
  org: org1
  tls_ca_cert: ../../artifacts/channel/crypto-config/ordererOrganizations/example.com/msp/tlscacerts/tlsca.example.com-cert.pem

# Peer Nodes to interact with as endorsement Peers
endorsers:
  - *peer1
  - *peer2
  - *peer3

# Peer Nodes to interact with as Commit Peers as listening
committers: 
  - *peer1
  - *peer2
  - *peer3
# we might support multi-committer in the future for more complex test scenario.
# i.e. consider tx committed only if it's done on >50% of nodes. 
# Give your commit Threshold as numbers for peers here.
commitThreshold: 1

# orderer Nodes to interact with
orderer: *orderer

policyFile: ./orLogic.rego
# policyFile: ./andLogic.rego


# Invocation configs
channel: mychannel
chaincode: supplychain-chaincode
# chain code args below, in a list of str
# we provides 3 kinds of randmon
# uuid
# randomString$length
# randomNumber$min_$max
args:
  - CreateAssetTape
  - uuid
  - randomString8
  - randomNumber0_50
  - randomString8
  - randomNumber0_50
# Tx submiter information
mspid: Org1MSP
private_key: ../../artifacts/channel/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk
sign_cert: ../../artifacts/channel/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem
# network traffic control
num_of_conn: 20
client_per_conn: 20
