version: "2.1"

networks:
  test:

services:
  caliper:
    container_name: caliper
    image: hyperledger/caliper:0.6.0
    command: launch manager 
    environment:
      - CALIPER_BIND_SUT=fabric:fabric-gateway
      - CALIPER_BENCHCONFIG=benchmarks/config.yaml
      - CALIPER_NETWORKCONFIG=networks/network-config.yaml
      - MYMODULE_PERFORMANCE_SHOULDBEFAST=true
    volumes:
      - ./caliper-benchmarks-local:/hyperledger/caliper/workspace
      - ../../artifacts/channel/crypto-config:/hyperledger/caliper/workspace/crypto-config
    networks:
      - test
